{% set name = "brukeropusreader" %}
{% set version = environ['VERSION'] %}
{% set devstring = environ['DEVSTRING'] %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  path: ../

build:
  script_env:
    - VERSION
    - DEVSTRING
    - CONDA_BLD_PATH
  string: "{{ devstring }}"
  noarch: python
  script:
    - export SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
    - {{ PYTHON }} -m pip install .

requirements:
  build:
    - python
  host:
    - python
    - setuptools
    - setuptools_scm
    - numpy
    - pip
    - scipy
  run:
    - python
    - numpy
    - scipy
  test:
    - python             {{ python }}
    - pytest

test:
  script_env:
    - VERSION
    - DEVSTRING
    - CONDA_BLD_PATH
  imports:
    - brukeropusreader

about:
  home: "https://github.com/spectrochempy/brukeropusreader"
  license: GPLv3
  license_family: GPL3
  summary: "Bruker OPUS File Reader"

extra:
  recipe-maintainers:
    - fernandezc
