name: Build and publish packages 📦

on:
  push:
    branches:
      - master
      - develop

  pull_request:

  release:
    types: [published]

jobs:

  build_and_publish_conda_package:

    name: Build and publish Conda package to Anaconda
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash -l {0}

    steps:

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: "3.8"
          activate-environment: brukeropusreader
          environment-file: environment.yml
          auto-update-conda: true

      - name: Install brukeropusreader
        run: |
          python -m pip install .

      - name: Set up version environment variable
        run: |
          ## get version string from setuptools_scm
          PVS="$(python setup.py --version)"
          echo "Current version string = $PVS"

          ## Extract components
          IFS=$"+"
          read -ra arr <<< "$PVS"

          ## latest version string
          LATEST="${arr[0]}"
          IFS=$"."
          read -ra tag <<< "$LATEST";
          DEVSTRING="${tag[3]}"
          VERSION="${tag[0]}.${tag[1]}.${tag[2]}"
          if [[ -z $DEVSTRING ]]; then
            DEVSTRING="stable"
          fi

          ## Export variable in the github environment
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "DEVSTRING=$DEVSTRING" >> $GITHUB_ENV

          echo "$VERSION"
          echo "$DEVSTRING"

      - name: Build package
        run: |
          conda install conda-build conda-verify
          conda-build .conda --output-folder out

      - name: Publish package for release
        if: (github.event_name == 'release' && github.event.action == 'published' && github.repository == 'spectrochempy/brukeropusreader')
        env:
          ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        run: |
          conda install anaconda-client
          anaconda upload --force out/*/*.tar.bz2

      - name: Publish development package
        if: (github.event_name == 'push' && github.repository == 'spectrochempy/brukeropusreader')
        env:
          ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        run: |
          conda install anaconda-client
          anaconda upload -l dev --force out/*/*.tar.bz2
