name: Tests 🔬

on:
  push:

    branches:
      - master
      - develop

  pull_request:

  workflow_dispatch:

jobs:

  test-package:

    if: "!startsWith(github.ref, 'refs/release/')"

    name: Test using ${{ matrix.os }} and python ${{ matrix.pythonVersion }}

    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: bash -l {0}

    strategy:
      max-parallel: 4
      matrix:

        os: [ubuntu-latest] # , , macos-latest, windows-latest
        pythonVersion: ["3.10", "3.9", "3.8", "3.7"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python ${{ matrix.pythonVersion }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.pythonVersion }}

      - name: Install brukeropusreader
        run: |
          python3 -m pip install --upgrade pip setuptools wheel
          python3 -m pip install --upgrade numpy scipy 
          python3 -m pip install .

      - name: Test
        run: |
          # install dependencies for testing
          python3 -m pip install pytest pytest-doctestplus pytest-flake8
          pytest tests
